name: Update Submodules

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 0 * * *'  # everyday at 00:00
    
jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'  

      - name: Update submodules
        run: |
          git submodule update --remote --init --recursive
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
